[package]
name = "input"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = { version = "2.7", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
winit = { version = "0.25", features = ["serde"] }
