[workspace]
resolver = "2"
members = ["demo", "input", "camera", "graphics"]

[workspace.dependencies]
async-trait = "0.1.61"
bytemuck = { version = "1.12.3", features = ["derive"] }
crevice = "0.12.0"
crevice-derive = "0.10.0"
mint = "0.5.9"
thiserror = "1.0.38"
ultraviolet = { version = "0.9.0", features = ["mint"] }
winit = { version = "0.27.5", features = ["serde"] }
image = "0.24.5"
tokio = { version = "1.24.1", features = ["full"] }
bitflags = "1.3.2"
guillotiere = "0.6.2"
serde = { version = "1.0.152", features = ["derive"] }
camera = { path = "./camera", package = "ascending_camera"}
input = { path = "./input", package = "ascending_input" }
graphics = { path = "./graphics", package = "ascending_graphics" }
log = "0.4.17"
backtrace = "0.3.67"
once_cell = "1.17.0"
futures = "0.3.25"
cosmic-text = { git = "https://github.com/pop-os/cosmic-text" }
ordered-float = { version = "3.4.0", features = ["serde"] }
chrono = { version = "0.4.23", features = ["clock", "serde", "std"] }

[workspace.dependencies.naga]
#git = "https://github.com/gfx-rs/naga"
#rev = "b209d911"
version = "0.10.0"
features = ["span", "validate", "wgsl-in"]

[workspace.dependencies.wgpu]
#git = "https://github.com/gfx-rs/wgpu"
#rev = "061e04b"
version = "0.14.2"