[workspace]
resolver = "2"
members = ["demo", "input", "camera", "graphics"]

[workspace.dependencies]
async-trait = "0.1.68"
bytemuck = { version = "1.13.1", features = ["derive"] }
crevice = "0.13.0"
crevice-derive = "0.10.0"
mint = "0.5.9"
thiserror = "1.0.40"
winit = { version = "0.28.3", features = ["serde"] }
image = "0.24.6"
tokio = { version = "1.28.0", features = ["full"] }
guillotiere = "0.6.2"
serde = { version = "1.0.162", features = ["derive"] }
camera = { path = "./camera", package = "ascending_camera"}
input = { path = "./input", package = "ascending_input" }
graphics = { path = "./graphics", package = "ascending_graphics" }
log = "0.4.17"
backtrace = "0.3.67"
futures = "0.3.28"
cosmic-text = { git = "https://github.com/pop-os/cosmic-text" }
ordered-float = { version = "3.7.0", features = ["serde"] }
chrono = { version = "0.4.24", disable-defaults = true, features = ["clock", "serde", "std"] }
ubits = "0.3.1"
slab = "0.4.8"
lru = "0.10.0"
generational_array = "0.1.1"
ritehash = "0.2.0"
hecs = "0.10.3"
glam = { version = "0.24.0", features = ["bytemuck", "mint"] }
lyon = "1.0.1"

[workspace.dependencies.naga]
git = "https://github.com/gfx-rs/naga"
rev = "b99d58ea435090e561377949f428bce2c18451bb"
version = "0.12.0"
features = ["span", "validate", "wgsl-in"]

[workspace.dependencies.wgpu]
git = "https://github.com/gfx-rs/wgpu"
#rev = "061e04b"
features = ["expose-ids"]
version = "0.16.0"