[package]
name = "demo"
version = "0.1.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytemuck = { version = "1.7", features = ["derive"] }
crevice = "0.7"
crevice-derive = "0.7"
mint = "0.5"
naga = {git = "https://github.com/gfx-rs/naga.git", commit="28c4532", features = ["wgsl-in"]}
thiserror = "1.0"
ultraviolet = { version = "0.8", features = ["mint"] }
wgpu = {git = "https://github.com/gfx-rs/wgpu.git", commit="c824c8f"}
winit = { version = "0.25", features = ["serde"] }
image = "0.23"
tokio = { version = "1.8", features = ["full"] }
bitflags = "1.2.1"
guillotiere = "0.6.2"
serde = "1.0"
camera = { path = "../camera" }
input = { path = "../input" }
slog = "2.7.0"
sloggers = "2.0.0"
backtrace = "0.3"
lazy_static = "1.4.0"
log = "0.4.0"
env_logger = "0.9"