[package]
name = "demo"
version = "0.1.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
edition = "2021"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytemuck = { version = "1.7", features = ["derive"] }
crevice = "0.8"
crevice-derive = "0.8"
mint = "0.5"
naga = { git = "https://github.com/gfx-rs/naga.git", commit = "c69f676", features = [
    "wgsl-in",
] }
thiserror = "1.0"
ultraviolet = { version = "0.8", features = ["mint"] }
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", commit = "f8beffe" }
winit = { version = "0.26", features = ["serde"] }
image = "0.23"
tokio = { version = "1.14", features = ["full"] }
bitflags = "1.3"
guillotiere = "0.6"
serde = "1.0"
camera = { path = "../camera" }
input = { path = "../input" }
slog = "2.7"
sloggers = "2.1"
backtrace = "0.3"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.9"
pollster = "0.2.4"
wgpu_glyph = { git = "https://github.com/genusistimelord/wgpu_glyph.git" }
futures = "0.3"
