[package]
name = "demo"
version = "0.1.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
edition = "2021"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytemuck = { version = "1.8", features = ["derive"] }
crevice = "0.8"
crevice-derive = "0.8"
mint = "0.5"
thiserror = "1.0"
ultraviolet = { version = "0.9", features = ["mint"] }
winit = { version = "0.26", features = ["serde"] }
image = "0.24"
tokio = { version = "1.17", features = ["full"] }
bitflags = "1.3"
guillotiere = "0.6"
serde = "1.0"
camera = { path = "../camera" }
input = { path = "../input" }
slog = "2.7"
sloggers = "2.1"
backtrace = "0.3"
lazy_static = "1.4"
futures = "0.3"

[dependencies.naga]
git = "https://github.com/gfx-rs/naga"
rev = "1aa91549"
features = ["span", "validate", "wgsl-in"]

[dependencies.wgpu]
git = "https://github.com/gfx-rs/wgpu"
rev = "36f8d83"
